let adminKey='',data=[],stores=[],editing=null;const adminOrders=new Map();
function requireAdmin(){if(!adminKey)throw Error('請先登入總部');return adminKey;}
async function login(){try{const password=$('password').value;if(!password)throw Error('請輸入管理密碼');await call('login',{password});adminKey=password;$('password').value='';$('loginPanel').classList.add('hidden');$('adminContent').classList.remove('hidden');await refresh();newCampaign();}catch(e){adminKey='';$('loginPanel').classList.remove('hidden');$('adminContent').classList.add('hidden');notice(e.message,'error');}}
function logout(){adminKey='';data=[];stores=[];$('password').value='';$('adminContent').classList.add('hidden');$('loginPanel').classList.remove('hidden');notice('已登出','success');}
async function refresh(){try{const result=await call('adminData',{password:requireAdmin()});data=result.campaigns;stores=result.stores;$('titleInput').value=result.title;setTitle(result.title+'｜總部管理');renderStores();renderCampaigns();}catch(e){notice(e.message,'error');}}
async function saveTitle(){try{const title=await call('setTitle',{password:requireAdmin(),title:$('titleInput').value});setTitle(title+'｜總部管理');notice('網頁標題已更新','success');}catch(e){notice(e.message,'error');}}
function renderStores(){$('storeList').innerHTML=stores.length?stores.map((s,i)=>`<div class="bar"><strong>${safe(s)}</strong><button class="danger" type="button" data-remove-store="${i}">移除</button></div>`).join(''):'尚無門市。請先新增門市，加盟主才能下單。';}
async function addStore(){try{const name=$('newStore').value.trim();stores=await call('addStore',{password:requireAdmin(),name});$('newStore').value='';renderStores();notice('門市已新增','success');}catch(e){notice(e.message,'error');}}
async function removeStore(i){const name=stores[i];if(!name||!confirm(`確認移除「${name}」？歷史訂單仍保留。`))return;try{stores=await call('removeStore',{password:requireAdmin(),name});renderStores();notice('門市已從選單移除','success');}catch(e){notice(e.message,'error');}}
function newCampaign(){editing=null;$('editHeading').textContent='建立集單';['campaignTitle','starts','ends','description'].forEach(id=>$(id).value='');$('enabled').value='true';$('productEditors').innerHTML='';addProduct();}
function addProduct(p={}){const d=document.createElement('div');d.className='product-editor';d.dataset.id=p.id||'P'+crypto.randomUUID();d.innerHTML=`<div class="row"><div><label>商品名稱 *</label><input class="p-name" value="${safe(p.name)}"></div><div><label>圖片網址（https）</label><input class="p-image" type="url" value="${safe(p.image)}" placeholder="https://..."></div></div><div class="three"><div><label>批價 *</label><input class="p-cost" type="number" min="0" step="1" value="${p.cost??''}"></div><div><label>預計零售價</label><input class="p-retail" type="number" min="0" step="1" value="${p.retail??''}"></div><div><label>預計月租金</label><input class="p-rent" type="number" min="0" step="1" value="${p.rent??''}"></div></div><label>商品簡介</label><textarea class="p-intro">${safe(p.intro)}</textarea><label>採購參考網址</label><input class="p-url" type="url" value="${safe(p.url)}"><div class="actions"><button class="danger" type="button" data-remove-product>移除商品</button></div>`;$('productEditors').append(d);}
async function saveCampaign(){try{
  const editors=[...document.querySelectorAll('.product-editor')];
  const products=editors.map(d=>({id:d.dataset.id,name:d.querySelector('.p-name').value.trim(),image:d.querySelector('.p-image').value.trim(),cost:Number(d.querySelector('.p-cost').value),retail:Number(d.querySelector('.p-retail').value||0),rent:Number(d.querySelector('.p-rent').value||0),intro:d.querySelector('.p-intro').value.trim(),url:d.querySelector('.p-url').value.trim()}));
  const c={id:editing,title:$('campaignTitle').value.trim(),starts:$('starts').value,ends:$('ends').value,enabled:$('enabled').value==='true',description:$('description').value.trim(),products};
  if(!c.title||!c.starts||!c.ends||c.starts>=c.ends||!products.length||products.some(p=>!p.name||!Number.isFinite(p.cost)||p.cost<0)||editors.some(d=>d.querySelector('.p-cost').value===''))throw Error('請確認名稱、時間、商品名稱和批價；結束時間須晚於開始時間');
  if(products.some(p=>[p.image,p.url].some(u=>u&&!/^https:\/\//i.test(u))))throw Error('圖片及採購連結請使用 https 網址');
  await call('saveCampaign',{password:requireAdmin(),campaign:c});await refresh();newCampaign();notice('集單已儲存','success');
}catch(e){notice(e.message,'error');}}
function editCampaign(i){const c=data[i];if(!c)return;editing=c.id;$('editHeading').textContent='編輯集單';$('campaignTitle').value=c.title;$('starts').value=c.starts;$('ends').value=c.ends;$('enabled').value=String(c.enabled);$('description').value=c.description;$('productEditors').innerHTML='';c.products.forEach(addProduct);$('editHeading').scrollIntoView({behavior:'smooth'});}
function renderCampaigns(){$('adminCampaigns').innerHTML=data.length?data.map((c,i)=>`<div class="bar"><div><strong>${safe(c.title)}</strong> <span class="tag">${status(c)}</span><div class="muted">${safe(c.starts)} ～ ${safe(c.ends)} · ${c.products.length} 項商品</div></div><div class="actions"><button class="outline" type="button" data-edit="${i}">編輯</button><button type="button" data-summary="${i}">查看彙總</button></div></div><div id="sum-${i}"></div>`).join(''):'尚無活動';}
async function summary(i){try{
  const c=data[i],orders=await call('summary',{password:requireAdmin(),campaignId:c.id});
  adminOrders.set(c.id,orders);
  const sums=Object.fromEntries(c.products.map(p=>[p.id,0])),amounts=Object.fromEntries(c.products.map(p=>[p.id,0]));for(const o of orders)for(const item of o.items)if(item.productId in sums){sums[item.productId]+=Number(item.qty);amounts[item.productId]+=Number(item.qty)*Number(item.cost??c.products.find(p=>p.id===item.productId)?.cost??0);}
  const lines=c.products.map(p=>`<tr><td>${safe(p.name)}</td><td class="num">${sums[p.id]}</td><td class="num">${money(p.cost)}</td><td class="num">${money(amounts[p.id])}</td></tr>`).join('');
  const detail=orders.flatMap(o=>o.items.filter(item=>item.qty>0).map(item=>{const p=c.products.find(x=>x.id===item.productId);return `<tr><td>${safe(o.store)}</td><td>${safe(item.name||p?.name||'已移除商品')}</td><td class="num">${item.qty}</td><td class="num">${money(Number(item.cost??p?.cost??0)*item.qty)}</td><td>${safe(o.note)}</td></tr>`;})).join('');
  const receipts=orders.map((o,j)=>`<div class="bar"><div><strong>${safe(o.store)}</strong><div class="muted">${safe(showTime(o.updated))} · ${safe(o.id)}</div></div><div class="actions"><button class="outline" type="button" data-receipt="${i}" data-order="${j}">下載此店訂單明細</button><button class="outline" type="button" data-reset="${i}" data-order="${j}">重設查詢碼</button></div></div>`).join('');
  $(`sum-${i}`).innerHTML=`<div class="panel"><h3>商品彙總（${orders.length} 筆門市訂單）</h3><div class="scroll"><table><thead><tr><th>商品</th><th class="num">總數量</th><th class="num">批價</th><th class="num">金額</th></tr></thead><tbody>${lines}</tbody></table></div><h3 style="margin-top:22px">門市明細</h3><div class="scroll"><table><thead><tr><th>門市名稱</th><th>商品</th><th class="num">數量</th><th class="num">金額</th><th>備註</th></tr></thead><tbody>${detail||'<tr><td colspan="5">尚無訂單</td></tr>'}</tbody></table></div><h3 style="margin-top:22px">逐店訂單存檔</h3>${receipts||'<p>尚無訂單</p>'}<div class="actions"><button type="button" data-export="${i}">匯出 CSV</button></div></div>`;
}catch(e){notice(e.message,'error');}}
async function exportCsv(i){try{const c=data[i],orders=await call('summary',{password:requireAdmin(),campaignId:c.id});const rows=[['訂單編號','門市名稱','商品名稱','數量','批價','金額','備註','最後更新時間']];for(const o of orders)for(const item of o.items){if(item.qty<=0)continue;const p=c.products.find(x=>x.id===item.productId),cost=Number(item.cost??p?.cost??0);rows.push([o.id,o.store,item.name||p?.name||'已移除商品',item.qty,cost,item.qty*cost,o.note,o.updated]);}const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`${c.title}_集單明細.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000);}catch(e){notice(e.message,'error');}}
async function resetCode(i,j){try{const c=data[i],o=adminOrders.get(c.id)?.[j];if(!o)return;if(!confirm(`確定重設「${o.store}」的訂單查詢碼？舊碼會立即失效，請將新碼交給該門市。`))return;const result=await call('resetOrderCode',{password:requireAdmin(),campaignId:c.id,store:o.store});notice(`${result.store} 的新查詢碼：${result.code}。請立即保存並轉交門市；舊碼已失效。`,'success');}catch(e){notice(e.message,'error');}}
$('login').addEventListener('click',login);$('password').addEventListener('keydown',e=>{if(e.key==='Enter')login();});$('logout').addEventListener('click',logout);$('saveTitle').addEventListener('click',saveTitle);$('addStore').addEventListener('click',addStore);$('addProduct').addEventListener('click',()=>addProduct());$('saveCampaign').addEventListener('click',saveCampaign);$('newCampaign').addEventListener('click',newCampaign);
$('storeList').addEventListener('click',e=>{const b=e.target.closest('[data-remove-store]');if(b)removeStore(Number(b.dataset.removeStore));});
$('productEditors').addEventListener('click',e=>{if(e.target.matches('[data-remove-product]'))e.target.closest('.product-editor').remove();});
$('adminCampaigns').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit!==undefined)editCampaign(Number(b.dataset.edit));if(b.dataset.summary!==undefined)summary(Number(b.dataset.summary));if(b.dataset.export!==undefined)exportCsv(Number(b.dataset.export));if(b.dataset.reset!==undefined)resetCode(Number(b.dataset.reset),Number(b.dataset.order));if(b.dataset.receipt!==undefined){const i=Number(b.dataset.receipt),c=data[i],o=adminOrders.get(c.id)?.[Number(b.dataset.order)];if(o)downloadReceipt(c,o);}});
